swagger:
  enabled: true
  api:
    info:
      title: "Potato Application"
      description: "Service for representing a \"Potato Market\""
      version: "1.0"
      contact:
        name: "Tibor Kov√°cs"
        email: "kovacs1tibor@gmail.com"

spring.datasource:
  driverClassName: "org.h2.Driver"
  url: "jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE"
  username: "test"
  password: "test"
